### ISSUE TITLE
Detail package installation for non CRAN package (e.g. patchwork)

### ISSUE THREAD

**Issue by courtiol** [Z3tt/Z3tt#2]
Hi @Z3tt,
you wrote:
https://github.com/Z3tt/Z3tt/blob/469531c7ce7460b103ee546b9e21bba0d80d8044/content/post/2019-08-05_ggplot2-tutorial.Rmd#L74-L79
but last time I checked, __patchwork__ was not on CRAN and thus you may want to explain how to install that [`remotes::install_github("thomasp85/patchwork")` after installing __remotes__].
++

**Comment by z3tt** [comment]
Hi Alex, thanks for mentioning this, my bad. I totally missed this and this chunk was never run. And also I still can't believe it's not on CRAN yet even though I know it.
